Решения заданий 3 урока
scolotin/popular-libs pull request #3
Opened 2021-06-04 08:48 UTC by scolotin

2021-06-08 09:24 UTC, PeterBukhal-sovcombank requested changes
Исправить недочеты пока не принимаю.

2021-06-08 09:24 UTC, PeterBukhal-sovcombank commented on app/src/main/java/com/scolotin/popularlibs/repositories/GithubUsersRepo.kt
> +    fun getUsers(): Observable<GithubUser> {
в данном случае просто нужно вернуть весь список, пользователей одним списком, но Observable.fromIterable() превращает список в поток сигналов из каждого элемента списка. в этом случае правильней использовать Single.just()

2021-06-08 09:24 UTC, PeterBukhal-sovcombank commented on app/src/main/java/com/scolotin/popularlibs/presenter/UsersPresenter.kt
> +    private var disposable: Disposable? = null
Так же тут упущен важный момент про который мы говорили на вебинаре, это отмена цепочки в случае необходимости. В текущем виде этот момент не реализован, нужно использовать Disposable и отменить цепочку как минимум в методе презентера onDestroy. Не вижу отмены подписки.

2021-06-08 19:51 UTC, scolotin commented on app/src/main/java/com/scolotin/popularlibs/repositories/GithubUsersRepo.kt
> +    fun getUsers(): Observable<GithubUser> {
Внёс исправления.

2021-06-08 19:51 UTC, scolotin commented on app/src/main/java/com/scolotin/popularlibs/presenter/UsersPresenter.kt
> +    private var disposable: Disposable? = null
Внёс исправления.

2021-06-11 12:19 UTC, PeterBukhal-sovcombank approved these changes

2021-06-12 19:25 UTC, merged